version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.9.0
    steps:
      - checkout
      - run:
          name: update
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install node modules reeeeee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: check the app builds
          command: npm run build
